Resolve #112: Add support for http HEAD method to RestClient
wultra/lime-java-core pull request #114
Opened 2022-10-03 11:09 UTC by saalistaja

All current GET endpoints on the test controller support also HEAD requests.

2022-10-03 11:11 UTC, saalistaja commented
I was considering removing the response body type from the methods (as HEAD request has no response body), but it stayed there to keep same patterns for all HTTP methods.

2022-10-04 05:19 UTC, banterCZ requested changes
Looks good, just typos in the documentation.

2022-10-04 05:19 UTC, banterCZ commented on README.md
> +- `head` - a blocking PATCH call with a generic request
```suggestion
- `head` - a blocking HEAD call with a generic request
```

2022-10-04 05:19 UTC, banterCZ commented on README.md
> +- `headNonBlocking` - a non-blocking PATCH call with a generic request with `onSuccess` and `onError` consumers
```suggestion
- `headNonBlocking` - a non-blocking HEAD call with a generic request with `onSuccess` and `onError` consumers
```

2022-10-04 05:19 UTC, banterCZ commented on README.md
> +- `headObject` - a blocking PATCH call with `ObjectRequest`
```suggestion
- `headObject` - a blocking HEAD call with `ObjectRequest`
```

2022-10-04 08:13 UTC, saalistaja commented on README.md
> +- `head` - a blocking PATCH call with a generic request
ouch, thanks

2022-10-04 08:29 UTC, banterCZ approved these changes

2022-10-04 09:43 UTC, romanstrobl approved these changes
Useful addition. We can keep the empty response classes, this is fine.

2022-10-05 07:43 UTC, merged