Add support for http PATCH method to RestClient
wultra/lime-java-core pull request #91
Opened 2022-05-25 11:48 UTC by banterCZ

2022-05-26 20:54 UTC, petrdvorak approved these changes
Looks good

2022-05-27 06:28 UTC, saalistaja approved these changes

2022-05-30 19:36 UTC, romanstrobl requested changes
Can you please update the documentation, too? Thanks.

2022-06-06 04:36 UTC, banterCZ commented on README.md
> +- `patchNonBlocking` - a non-blocking PUT call with a generic request / response with `onSuccess` and `onError` consumers
Ups, wrong find/replace, fixed.

2022-06-06 07:59 UTC, romanstrobl approved these changes
Approved.

2022-06-06 08:13 UTC, merged